# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false

# Static resources (disable cache in development)
spring.web.resources.cache.period=0

